import {StyleSheet} from 'react-native'

import Colors from '../constants/Colors'

export const styles = StyleSheet.create({
    header: {
        flexDirection: 'row',
        height: 100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    back: {
        width: 100,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    title: {
        textAlign: 'center',
        fontSize: 24,
        color: Colors.PRIMARY,
    },
    desc: {
        textAlign: 'center',
        fontSize: 12,
        color: Colors.PRIMARY,
    },
    option: {
        flexDirection: 'row',
        margin: 5,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.LIGHTER_GRAY,
        borderRadius: 10,
        shadowColor: Colors.GRAY,
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.8,
        shadowRadius: 1,
        elevation: 5,
        height: 100,
    },
    imgCont: {
        width: 95,
        height: 95,
        backgroundColor: Colors.LIGHT_GRAY,
        alignItems: 'center',
        justifyContent: 'center',
        borderTopLeftRadius: 10,
        borderBottomLeftRadius: 10,
    },
    imgSize: {
        width: 75,
        height: 75,
    },
    subTextStyle: {
        fontSize: 14,
        color: Colors.PRIMARY,
    },
})

export const architecturePkgStyles = StyleSheet.create({
    center: {
        flexDirection: 'row',
        height: 100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    goBack: {
        width: 100,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    headerTitle: {
        flex: 1,
        textAlign: 'center',
        marginLeft: -100,
        fontSize: 20,
        color: Colors.PRIMARY,
    },
    features: {
        padding: 10,
        fontWeight: 'bold',
        color: Colors.PRIMARY,
    },
    pkgItem: {
        padding: 5,
        paddingHorizontal: 10,
        marginVertical: 1,
        backgroundColor: Colors.WHITE,
        borderRadius: 5,
        flexDirection: 'row',
    },
    pkgItemText: {
        flex: 1,
        color: Colors.PRIMARY,
    },
    bold: {
        padding: 10,
        fontWeight: 'bold',
        color: Colors.PRIMARY,
    },
    selectedOption: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: Colors.GREEN,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        top: 10,
        right: 10,
    },
    option: {
        flexDirection: 'row',
        margin: 5,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.LIGHTER_GRAY,
        borderRadius: 10,
        shadowColor: Colors.GRAY,
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.8,
        shadowRadius: 1,
        elevation: 5,
        height: 100,
    },
    shadow: {
        margin: 5,
        justifyContent: 'center',
        backgroundColor: Colors.LIGHTER_GRAY,
        borderRadius: 10,
        shadowColor: Colors.GRAY,
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.8,
        shadowRadius: 1,
        elevation: 5,
        padding: 16,
    },
    support: {
        flexDirection: 'row',
        margin: 5,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.LIGHTER_GRAY,
        borderRadius: 5,
        shadowColor: Colors.GRAY,
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.8,
        shadowRadius: 1,
        elevation: 5,
        height: 100,
    },
    commImg: {
        width: 85,
        height: 85,
        marginLeft: 7,
    },
    itemText: {
        padding: 10,
        flex: 1,
        fontSize: 16,
        fontWeight: 'bold',
        color: Colors.PRIMARY,
    },
    quotationBtn: {
        flexDirection: 'row',
        height: 50,
        width: 300,
        backgroundColor: Colors.PRIMARY,
        marginTop: 10,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    contactContainer: {
        flexDirection: 'row',
        width: 90,
        height: 28,
        backgroundColor: Colors.PRIMARY,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 5,
        padding: 5,
        marginTop: 5,
    },
})
