import {Dimensions, StyleSheet} from 'react-native'
import Colors from '../constants/Colors'

const {width, height} = Dimensions.get('window')

export const ArchitectureFormStyles = StyleSheet.create({
    recordingText: {
        color: Colors.SECONDARY,
        fontSize: 18,
    },
    service: {
        flex: 1,
        textAlign: 'center',
        marginLeft: -100,
        fontSize: 20,
        color: Colors.PRIMARY,
    },
    row: {
        flexDirection: 'row',
    },
    del: {
        flexDirection: 'row-reverse',
        width: 50,
        borderLeftColor: Colors.SECONDARY,
        borderLeftWidth: 1,
    },
    center: {
        flexDirection: 'row',
        height: 100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    arrowLeft: {
        width: 60,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    serviceStyle: {
        flex: 1,
        textAlign: 'center',
        marginLeft: -100,
        fontSize: 24,
        color: Colors.PRIMARY,
    },
    bold: {
        fontSize: 14,
        fontWeight: 'bold',
        color: Colors.PRIMARY,
    },
    itemImage: {
        width: (width - 32) / 3 - 10,
        height: (width - 32) / 3 - 10,
    },
    inputCont: {
        backgroundColor: Colors.WHITE,
        borderRadius: 5,
        padding: 10,
        marginTop: 15,
        height: 150,
        width: width - 32,
    },
    recordingView: {
        flexDirection: 'row',
        backgroundColor: Colors.PRIMARY,
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        borderRadius: 5,
    },
    desc: {
        fontSize: 14,
        fontWeight: 'bold',
        marginTop: 10,
        color: Colors.PRIMARY,
    },
    mapModalStyle: {
        flexDirection: 'row',
        backgroundColor: Colors.WHITE,
        borderRadius: 5,
        padding: 5,
        marginTop: 15,
        width: width - 32,
    },
    detailsInputStyle: {
        width: width - 32,
        height: 150,
        textAlignVertical: 'top',
        color: Colors.PRIMARY,
    },
    textBold: {
        fontWeight: 'bold',
        color: Colors.PRIMARY,
    },
    attachPics: {
        fontSize: 14,
        fontWeight: 'bold',
        marginTop: 15,
        color: Colors.PRIMARY,
    },
    mediaCont: {
        width: width - 32,
        borderColor: Colors.GRAY,
        borderWidth: 1,
        backgroundColor: Colors.WHITE,
        marginTop: 15,
        borderRadius: 5,
        borderStyle: 'dashed',
        padding: 3,
    },
    sectionMargin: {
        marginVertical: 16,
        fontSize: 16,
        color: Colors.PRIMARY,
    },
    imageContainer: {
        width: (width - 32) / 3,
        height: (width - 32) / 3,
    },
    delPic: {
        position: 'absolute',
        top: 5,
        right: 5,
        width: 24,
        height: 24,
        borderRadius: 2,
        backgroundColor: Colors.RED,
        justifyContent: 'center',
        alignItems: 'center',
    },
    imageModalCont: {
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
    },
    imageModal: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: Colors.SECONDARY,
        justifyContent: 'center',
        alignItems: 'center',
    },
    centur: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    onSubmit: {
        flexDirection: 'row',
        height: 40,
        width: 150,
        backgroundColor: Colors.PRIMARY,
        marginTop: 10,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    submitText: {
        color: Colors.SECONDARY,
        paddingRight: 5,
    },
    openMapModal: {
        flexDirection: 'row',
        height: 56,
        backgroundColor: Colors.WHITE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    openMapClick: {
        width: 50,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
    },
    locationText: {
        flex: 1,
        fontSize: 18,
        color: Colors.PRIMARY,
    },
    autoCompleteCont: {
        position: 'absolute',
        top: 10,
        left: 10,
        width: width - 20,
        backgroundColor: Colors.WHITE,
    },
    mapMarker: {
        flexDirection: 'row',
        position: 'absolute',
        left: 16,
        bottom: 75,
        borderRadius: 10,
        height: 60,
        width: width - 32,
        backgroundColor: Colors.WHITE,
        borderColor: Colors.LIGHT_GRAY,
        borderWidth: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    closeMapModal: {
        position: 'absolute',
        left: 16,
        bottom: 16,
        borderRadius: 25,
        height: 50,
        width: width - 32,
        backgroundColor: Colors.PRIMARY,
        justifyContent: 'center',
        alignItems: 'center',
    },
    confirmLocText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: Colors.SECONDARY,
    },
    mapPin: {
        position: 'absolute',
        top: height / 2 - 66,
        left: width / 2 - 16,
    },
    darkOpacity: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: Colors.DARK_OPACITY,
    },
    openCamCont: {
        height: 150,
        backgroundColor: Colors.WHITE,
        padding: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        borderTopColor: Colors.SECONDARY,
        borderTopWidth: 5,
    },
    openCam: {
        width: 100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    progressBarPercentage: {
        backgroundColor: Colors.GREEN,
        height: 10,
        borderRadius: 3,
    },
    progressBarStyle: {
        height: 10,
        borderRadius: 3,
        backgroundColor: Colors.GRAY,
        marginTop: 10,
        width: width - 40,
    },
    picUploadCont: {
        height: 150,
        backgroundColor: Colors.WHITE,
        padding: 20,
    },
    textSmall: {
        marginTop: 10,
        color: Colors.PRIMARY,
    },
    support: {
        flexDirection: 'row',
        margin: 5,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.LIGHTER_GRAY,
        borderRadius: 5,
        shadowColor: Colors.GRAY,
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.8,
        shadowRadius: 1,
        elevation: 5,
        height: 100,
    },
    shadow: {
        shadowColor: Colors.GRAY,
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.8,
        shadowRadius: 1,
        elevation: 5,
    },
    backgroundVideo: {
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
        width: 100,
        height: 100,
    },
    picsStyle: {
        marginTop: 10,
        color: Colors.PRIMARY,
    },
})

export const ProgressModalStyles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: Colors.DARK_OPACITY,
    },
    modalStyle: {
        height: 150,
        backgroundColor: Colors.WHITE,
        padding: 20,
    },
    percentageBar: {
        backgroundColor: Colors.GREEN,
        height: 10,
        borderRadius: 3,
    },
    barContainer: {
        height: 10,
        borderRadius: 3,
        backgroundColor: Colors.GRAY,
        marginTop: 10,
        width: width - 40,
    },
    contactIconContainer: {
        width: 100,
        height: 100,
        backgroundColor: Colors.PRIMARY,
        alignItems: 'center',
        justifyContent: 'center',
        borderTopLeftRadius: 10,
        borderBottomLeftRadius: 10,
    },
    numberContainer: {
        flexDirection: 'row',
        width: 90,
        height: 28,
        backgroundColor: Colors.PRIMARY,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 5,
        padding: 5,
        marginTop: 5,
    },
})
